import { useState, useEffect } from 'react';

// Simple translations for the app
const translations = {
  en: {
    home: 'Home',
    addItem: 'Add Item',
    settings: 'Settings',
    appTitle: 'Food Tracker',
    saveError: 'Save Error',
    notifications: 'Notifications',
    expiryReminder: 'Expiry Reminder',
    foodDetails: 'Food Details',
    foodList: 'Food List',
    onboarding: 'Onboarding',
    privacyPolicy: 'Privacy Policy',
    subscription: 'Subscription',
    emptyState: 'No items found',
    statsCard: 'Statistics',
    voiceSettings: 'Voice Settings',
    heroSlideshow: 'Featured Items',
    foodCard: 'Food Item',
    // Rating system
    rateThisItem: 'Rate This Item',
    selectRating: 'Select Rating',
    terrible: 'Terrible',
    poor: 'Poor',
    average: 'Average',
    good: 'Good',
    excellent: 'Excellent',
    howWasIt: 'How was it?',
    addComment: 'Add Comment',
    shareYourExperience: 'Share your experience...',
    submitRating: 'Submit Rating',
    submitting: 'Submitting...',
    ratingSubmitted: 'Rating submitted successfully!',
    ratingSubmissionError: 'Failed to submit rating',
    pleaseSelectRating: 'Please select a rating',
    // Tags
    fresh: 'Fresh',
    tasty: 'Tasty',
    expired: 'Expired',
    waste: 'Waste',
    healthy: 'Healthy',
    delicious: 'Delicious',
    spoiled: 'Spoiled',
    perfect: 'Perfect',
    // Feedback
    sendFeedback: 'Send Feedback',
    feedbackType: 'Feedback Type',
    reportBug: 'Report Bug',
    requestFeature: 'Request Feature',
    suggestImprovement: 'Suggest Improvement',
    generalFeedback: 'General Feedback',
    title: 'Title',
    description: 'Description',
    enterTitle: 'Enter title...',
    enterDescription: 'Describe your feedback...',
    overallRating: 'Overall Rating',
    emailOptional: 'Email (Optional)',
    enterEmail: 'Enter your email...',
    emailNote: 'We may contact you for follow-up',
    submitFeedback: 'Submit Feedback',
    feedbackSubmitted: 'Feedback submitted successfully!',
    feedbackSubmissionError: 'Failed to submit feedback',
    pleaseSelectFeedbackType: 'Please select feedback type',
    pleaseFillTitle: 'Please fill in the title',
    pleaseFillDescription: 'Please fill in the description',
    // Ratings display
    userRatings: 'User Ratings',
    viewAll: 'View All',
    basedOnRatings: 'Based on {count} ratings',
    commonTags: 'Common Tags',
    ratingsAndReviews: 'Ratings & Reviews',
    recentRatings: 'Recent Ratings',
    noRatingsYet: 'No ratings yet',
    startRatingItems: 'Start rating your items to see reviews here',
    viewAndManageRatings: 'View and manage your ratings',
    helpUsImprove: 'Help us improve the app',
  },
  zh: {
    home: '首页',
    addItem: '添加项目',
    settings: '设置',
    appTitle: '食物追踪器',
    saveError: '保存错误',
    notifications: '通知',
    expiryReminder: '过期提醒',
    foodDetails: '食物详情',
    foodList: '食物列表',
    onboarding: '引导页面',
    privacyPolicy: '隐私政策',
    subscription: '订阅',
    emptyState: '未找到项目',
    statsCard: '统计',
    voiceSettings: '语音设置',
    heroSlideshow: '精选项目',
    foodCard: '食物项目',
    // Rating system
    rateThisItem: '为此物品评分',
    selectRating: '选择评分',
    terrible: '很差',
    poor: '较差',
    average: '一般',
    good: '不错',
    excellent: '很棒',
    howWasIt: '感觉如何？',
    addComment: '添加评论',
    shareYourExperience: '分享您的体验...',
    submitRating: '提交评分',
    submitting: '提交中...',
    ratingSubmitted: '评分提交成功！',
    ratingSubmissionError: '评分提交失败',
    pleaseSelectRating: '请选择评分',
    // Tags
    fresh: '新鲜',
    tasty: '美味',
    expired: '过期',
    waste: '浪费',
    healthy: '健康',
    delicious: '好吃',
    spoiled: '变质',
    perfect: '完美',
    // Feedback
    sendFeedback: '发送反馈',
    feedbackType: '反馈类型',
    reportBug: '报告错误',
    requestFeature: '功能请求',
    suggestImprovement: '改进建议',
    generalFeedback: '一般反馈',
    title: '标题',
    description: '描述',
    enterTitle: '输入标题...',
    enterDescription: '描述您的反馈...',
    overallRating: '总体评分',
    emailOptional: '邮箱（可选）',
    enterEmail: '输入您的邮箱...',
    emailNote: '我们可能会联系您进行后续跟进',
    submitFeedback: '提交反馈',
    feedbackSubmitted: '反馈提交成功！',
    feedbackSubmissionError: '反馈提交失败',
    pleaseSelectFeedbackType: '请选择反馈类型',
    pleaseFillTitle: '请填写标题',
    pleaseFillDescription: '请填写描述',
    // Ratings display
    userRatings: '用户评分',
    viewAll: '查看全部',
    basedOnRatings: '基于 {count} 个评分',
    commonTags: '常见标签',
    ratingsAndReviews: '评分与评论',
    recentRatings: '最近评分',
    noRatingsYet: '暂无评分',
    startRatingItems: '开始为您的物品评分以查看评论',
    viewAndManageRatings: '查看和管理您的评分',
    helpUsImprove: '帮助我们改进应用',
  },
};

type Language = keyof typeof translations;
type TranslationKey = keyof typeof translations.en;

export function useLanguage() {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return {
    language,
    setLanguage,
    t,
  };
}